spring:
  datasource:
    url: jdbc:mysql://localhost:3308/harish
    username: root
    password: Harish@1
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: harishjavabean1@gmail.com
    password: Welcome@Testing
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8090
